# Generated by Django 2.1.7 on 2019-03-15 04:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=31, unique=True, verbose_name='設定名')),
                ('similarity', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='類似度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('hero', models.CharField(default='ヒロイン', max_length=63, verbose_name='主人公')),
            ],
        ),
    ]
