# Generated by Django 2.1.7 on 2019-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20190315_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='sheet_name',
            field=models.CharField(default='Story', max_length=31, verbose_name='読み込みシート名'),
        ),
    ]
