export const GET_SETTINGS = "GET_SETTINGS";
export const SELECT_SETTINGS = "SELECT_SETTINGS";
export const GET_CHARA_NAMES = "GET_CHARA_NAMES";
export const POST_CHARA_NAMES = "POST_CAHRA_NAMES";

export const INPUT_EXCEL_FILES = "INPUT_EXCEL_FILES";
export const IDENTIFY_FILE = "IDENTIFY_FILE";
export const RESET_TEXT = "RESET_TEXT";
export const RESET_EXCEL_FILES = "RESET_EXCEL_FILES";
export const CHANGE_TEXT = "CHANGE_TEXT";
export const CONVERT_TEXT_TO_LIST = "CONVERT_TEXT_TO_LIST";
export const GENERATE_DEFF_FILES = "GENERATE_DEFF_FILES";
export const CHANGE_SHEET_NAME = "CHANGE_SHEET_NAME";
export const CAHNGE_VERSION = "CHANGE_VERSION";
export const CHANGE_NAME_DETECTION = "CHANGE_NAME_DETECTION";
export const TOGGLE_NAME_EVALUATION = "TOGGLE_NAME_EVALUATION";
export const CHANGE_NAME_EVALUATION_REAR = "CHANGE_NAME_EVALUATION_REAR"; 
export const RESET_NAME_EVALUATION = "RESET_NAME_EVALUATION";